# Assignment 1 Numpy Basics

### Exercise 1: Create a 4X2 integer array and Print its attributes. 

Note: The element must be a type of unsigned int16. And print the following Attributes: –

. The shape of an array.

. Array dimensions.

. The Length of each element of the array in bytes.

In [23]:
import numpy as np
data = np.empty([4,2], dtype = np.uint16) 
print("Printing Array\n")
print(data,"\n")

print("Printing numpy array Attributes\n")
print("1> Array Shape is: ", data.shape)
print("2>. Array dimensions are ", data.ndim)
print("3>. Length of each element of array in bytes is ", data.itemsize)

Printing Array

[[ 4118 51861]
 [39248 65158]
 [ 8736 40080]
 [ 7253 19105]] 

Printing numpy array Attributes

1> Array Shape is:  (4, 2)
2>. Array dimensions are  2
3>. Length of each element of array in bytes is  2


### Exercise 2: Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10. 


In [24]:
import numpy as np

print("Creating 5X2 array using numpy.arange")
data = np.arange(100, 200, 10)
data = data.reshape(5,2)
print (data)

Creating 5X2 array using numpy.arange
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


### Exercise 3: Following is the provided numpy array. return array of items in the second column from all rows.

sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]]) 


In [25]:
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]]) 

In [34]:
import numpy as np

sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]]) 
print("Printing Input Array")
print(sampleArray,"\n")

print("Printing array of items in the second column from all rows")
updatedArray = sampleArray[...,1]
print(updatedArray)

Printing Input Array
[[11 22 33]
 [44 55 66]
 [77 88 99]] 

Printing array of items in the second column from all rows
[22 55 88]


### Exercise 4: Following is the given numpy array return array of odd rows and even columns.

sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24],
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]]) 

In [31]:
import numpy as np

sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]]) 
print("Printing Input Array")
print(sampleArray,"\n")

print(" Printing array of odd rows and even columns")
updatedArray = sampleArray[::2, 1::2]
print(updatedArray)

Printing Input Array
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]] 

 Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]


### Exercise 5: Add the following two NumPy arrays. 

arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]]) 

In [35]:
import numpy as np

arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])

addition  = arrayOne + arrayTwo
print("addition of two arrays is \n")
print(addition)

addition of two arrays is 

[[20 39 33]
 [25 25 28]]
